services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "11000:3000"
    depends_on:
      - backend

  frontend-app:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    ports:
      - "11001:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      APP_ALLOWED_ORIGINS: >-
        https://escape-meeting.private-web.tossmini.com,
        https://escape-meeting.web.tossmini.com
    ports:
      - "11002:8080"
